name: Lint
on:
  push:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/node-setup
        with:
          use-matrix: true

      - name: Lint package
        run: pnpm run lint
