name: Lint
on:
  push:
    branches:
      - "**"

jobs:
  lint:
    uses: ./.github/workflows/reusable-matrix.yml
    with:
      use-matrix: true
      run-command: pnpm run lint
      run-command-description: Lint
