name: Publish
on:
  push:
    branches:
      - "**"
      #- main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    uses: ./.github/workflows/reusable-matrix.yml
    with:
      use-matrix: true
      run-command: pnpm run test
      run-command-description: Test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4

      - name: Create Changeset PR
        id: changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
